[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"

[[headers]]
  for = "/src/*"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"

[[headers]]
  for = "/scripts/*"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"

[[headers]]
  for = "/models/*.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/data/*.json"
  [headers.values]
    Content-Type = "application/json"
